name: A workflow for Jmeter Tests
on: push

jobs:
  build:
    name: Jmeter Test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.2.0
        with:
          testFilePath: load/examen_test_plan.jmx
          outputReportsFolder: reports/
  test:
    name: newman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: api/newman/examen.postman_collection.json
          reporters: cli
          environment: api/newman/herokuexamen.postman_environment.json

      - name: Output summary to console
        run: echo ${{ steps.run-api-tests.outputs.summary }}
  mvn:
    name: maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Maven
        uses: stCarolas/setup-maven@v3
        with:
          maven-version: 3.5.4
      - name: Run Tests
        run: cd api/rest_assured && mvn clean test
      
          